name: Publish Production Docker

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_REPO: ghcr.io/${{ github.repository }}

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag session-matcher-backend
    - name: Docker login using Github Token
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Deploy Docker Image
      run: |
        docker tag session-matcher-backend ghcr.io/${{ env.IMAGE_REPO }}/session-matcher-backend
        docker push ghcr.io/${{ env.IMAGE_REPO }}/session-matcher-backend
